---
- name: Create and configure matterhorn and avalon users
  include_tasks: users.yml

- name: Create necessary directories
  include_tasks: setup_dirs.yml
 
- name: Configure and launch Matterhorn
  include_tasks: matterhorn_config.yml